osx builds also need -DDISABLE_BSYMBOLIC=ON

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -128,7 +128,11 @@ before_script:
   - set +e 
   - mkdir -p build || echo "Failed to mkdir build"
   - cd build || echo "Failed to cd build"
-  - cmake .. || echo "Failed to run cmake"
+  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
+       cmake -DDISABLE_BSYMBOLIC=ON .. ;
+    else 
+       cmake .. ;
+    fi || echo "Failed to run cmake"
 
 script:
   - make
